services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: backend
    image: salepos-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - smart-salepos-network

  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: frontend
    image: salepos-frontend:latest
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - smart-salepos-network

networks:
  smart-salepos-network:
    driver: bridge
